# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "866284d78be7772c0243a45ebfb99c69"
application_url = "https://whtasappshopifyapp.vercel.app/apps/default-app-home"
embedded = true
name = "whatsapp-offers"

[access_scopes]
# Learn more at https://whtasappshopifyapp.vercel.app/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,write_products"

[auth]
redirect_urls = [ "https://whtasappshopifyapp.vercel.app/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"


