# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "whatsapp-offers"
client_id = "" # filled in automatically after `shopify app config link`, or paste your Client ID here
application_url = "https://whtasappshopifyapp.vercel.app"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers,write_products,read_fulfillments"

[auth]
redirect_urls = [
  "https://whtasappshopifyapp.vercel.app/auth/callback",
  "https://whtasappshopifyapp.vercel.app/auth/shopify/callback",
  "https://whtasappshopifyapp.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[app_proxy]
url = "https://whtasappshopifyapp.vercel.app/api/optin"
subpath = "whatsapp-offers"
prefix = "apps"

[pos]
embedded = false
