# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "afd65960afd4db07ce60f92168d1c716"
name = "Watsapp offers & Alerts"
application_url = "https://watsappsofferapp.vercel.app"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers,write_products,read_fulfillments,read_discounts"

[auth]
redirect_urls = [
  "https://watsappsofferapp.vercel.app/auth/callback",
  "https://watsappsofferapp.vercel.app/auth/shopify/callback",
  "https://watsappsofferapp.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[app_proxy]
url = "https://watsappsofferapp.vercel.app/api/proxy"
subpath = "whatsapp-offers"
prefix = "apps"

[pos]
embedded = false